// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiner8MF3Tys8MaQw8OCAtdEqf7PmF4UQ',
    appId: '1:255266167372:web:b1b324f233738a8fef32e9',
    messagingSenderId: '255266167372',
    projectId: 'my-restaurant-app-de879',
    authDomain: 'my-restaurant-app-de879.firebaseapp.com',
    storageBucket: 'my-restaurant-app-de879.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSkcwXz4u059zbV9NuGOQloppydaV83CA',
    appId: '1:255266167372:android:5da4082a4c8ee4daef32e9',
    messagingSenderId: '255266167372',
    projectId: 'my-restaurant-app-de879',
    authDomain: 'my-restaurant-app-de879.firebaseapp.com',
    storageBucket: 'my-restaurant-app-de879.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiner8MF3Tys8MaQw8OCAtdEqf7PmF4UQ',
    appId: '1:255266167372:web:8693783fac4eeaa8ef32e9',
    messagingSenderId: '255266167372',
    projectId: 'my-restaurant-app-de879',
    authDomain: 'my-restaurant-app-de879.firebaseapp.com',
    storageBucket: 'my-restaurant-app-de879.firebasestorage.app',
  );
}
